export const mockBoards = [
  {
    id: "1",
    title: "Marketing Creativo",
    description: "Plan de campañas para nuevos productos",
    coverImage: "/assets/images/img1.jpg",
    updatedAt: "2025-07-24T10:00:00Z",
    isFavorite: true, // ✅ FAVORITO ORIGINAL
    members: [
      { id: "u1", name: "Lucía", avatar: "/assets/icons/avatar1.png" },
      { id: "u2", name: "Pedro", avatar: "/assets/icons/avatar2.png" },
    ],
    tags: ["Publicidad", "Diseño"],
  },
  {
    id: "nuevo1", // 🆕 Nuevo primer tablero de "creados"
    title: "Campaña Internacional",
    description: "Ideas para el lanzamiento global",
    coverImage: "/assets/images/img4.jpg", // ✅ Imagen nueva
    updatedAt: "2025-07-25T09:00:00Z",
    isFavorite: false,
    members: [
      { id: "u37", name: "Marcos", avatar: "/assets/icons/avatar3.png" },
      { id: "u38", name: "Julia", avatar: "/assets/icons/avatar1.png" },
      { id: "u39", name: "Sergio", avatar: "/assets/icons/avatar2.png" },
      { id: "u40", name: "Carmen", avatar: "/assets/icons/avatar3.png" },
    ],
    tags: ["Lanzamiento", "Global"],
  },
  {
    id: "2",
    title: "Sprint Frontend",
    description: "Implementación de vistas responsivas",
    coverImage: "/assets/images/img2.jpg",
    updatedAt: "2025-07-23T14:30:00Z",
    isFavorite: false,
    members: [
      { id: "u3", name: "Ana", avatar: "/assets/icons/avatar3.png" },
      { id: "u4", name: "Luis", avatar: "/assets/icons/avatar2.png" },
      { id: "u5", name: "Tomás", avatar: "/assets/icons/avatar1.png" },
      { id: "u6", name: "Camila", avatar: "/assets/icons/avatar3.png" },
    ],
    tags: ["React", "Tailwind"],
  },
  {
    id: "3",
    title: "Tablero de Diseño",
    description: "Exploración de nuevas interfaces",
    coverImage: "/assets/images/img3.jpg",
    updatedAt: "2025-07-22T10:00:00Z",
    isFavorite: false,
    members: [
      { id: "u7", name: "Verónica", avatar: "/assets/icons/avatar1.png" },
      { id: "u8", name: "Carlos", avatar: "/assets/icons/avatar2.png" },
      { id: "u9", name: "Marta", avatar: "/assets/icons/avatar3.png" },
      { id: "u10", name: "Eduardo", avatar: "/assets/icons/avatar1.png" },
    ],
    tags: ["UI", "UX"],
  },
  {
    id: "4", // ✅ Duplicado del favorito en la fila creada
    title: "Marketing Creativo",
    description: "Plan de campañas para nuevos productos",
    coverImage: "/assets/images/img1.jpg",
    updatedAt: "2025-07-24T10:00:00Z",
    isFavorite: false, // ⚠️ Este se muestra como no favorito pero el frontend lo marca con corazón fucsia por el index === 3
    members: [
      { id: "u1", name: "Lucía", avatar: "/assets/icons/avatar1.png" },
      { id: "u2", name: "Pedro", avatar: "/assets/icons/avatar2.png" },
      { id: "u11", name: "Sofía", avatar: "/assets/icons/avatar3.png" },
      { id: "u12", name: "Raúl", avatar: "/assets/icons/avatar2.png" },
    ],
    tags: ["Publicidad", "Diseño"],
  },
  {
    id: "5",
    title: "Eventos Corporativos",
    description: "Organización de ferias y conferencias",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-20T08:15:00Z",
    isFavorite: false,
    members: [
      { id: "u13", name: "Esteban", avatar: "/assets/icons/avatar1.png" },
      { id: "u14", name: "Lina", avatar: "/assets/icons/avatar2.png" },
      { id: "u15", name: "Diego", avatar: "/assets/icons/avatar3.png" },
      { id: "u16", name: "María", avatar: "/assets/icons/avatar1.png" },
    ],
    tags: ["Eventos"],
  },
  {
    id: "6",
    title: "Estrategia Comercial",
    description: "Planes de expansión y ventas",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-20T09:30:00Z",
    isFavorite: false,
    members: [
      { id: "u17", name: "Paula", avatar: "/assets/icons/avatar2.png" },
      { id: "u18", name: "Jorge", avatar: "/assets/icons/avatar3.png" },
      { id: "u19", name: "Renata", avatar: "/assets/icons/avatar1.png" },
      { id: "u20", name: "Iván", avatar: "/assets/icons/avatar3.png" },
    ],
    tags: ["Ventas", "Negocios"],
  },
  {
    id: "7",
    title: "Backlog de bugs",
    description: "Seguimiento de errores pendientes",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-19T12:00:00Z",
    isFavorite: false,
    members: [
      { id: "u21", name: "Valentina", avatar: "/assets/icons/avatar2.png" },
      { id: "u22", name: "Julián", avatar: "/assets/icons/avatar3.png" },
      { id: "u23", name: "Elena", avatar: "/assets/icons/avatar1.png" },
      { id: "u24", name: "Andrés", avatar: "/assets/icons/avatar2.png" },
    ],
    tags: ["QA", "Soporte"],
  },
  {
    id: "8",
    title: "Reclutamiento",
    description: "Seguimiento de candidatos y vacantes",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-18T16:00:00Z",
    isFavorite: false,
    members: [
      { id: "u25", name: "Gabriela", avatar: "/assets/icons/avatar1.png" },
      { id: "u26", name: "David", avatar: "/assets/icons/avatar2.png" },
      { id: "u27", name: "Natalia", avatar: "/assets/icons/avatar3.png" },
      { id: "u28", name: "Ricardo", avatar: "/assets/icons/avatar2.png" },
    ],
    tags: ["RRHH"],
  },
  {
    id: "9",
    title: "Contabilidad",
    description: "Balances y reportes mensuales",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-17T18:45:00Z",
    isFavorite: false,
    members: [
      { id: "u29", name: "Fernando", avatar: "/assets/icons/avatar3.png" },
      { id: "u30", name: "Elisa", avatar: "/assets/icons/avatar1.png" },
      { id: "u31", name: "Bruno", avatar: "/assets/icons/avatar2.png" },
      { id: "u32", name: "Manuela", avatar: "/assets/icons/avatar3.png" },
    ],
    tags: ["Finanzas"],
  },
  {
    id: "10",
    title: "Capacitación Interna",
    description: "Formación del equipo técnico",
    coverImage: "/assets/images/default-board.jpg",
    updatedAt: "2025-07-16T09:15:00Z",
    isFavorite: false,
    members: [
      { id: "u33", name: "Álvaro", avatar: "/assets/icons/avatar1.png" },
      { id: "u34", name: "Camila", avatar: "/assets/icons/avatar2.png" },
      { id: "u35", name: "Raquel", avatar: "/assets/icons/avatar3.png" },
      { id: "u36", name: "Ignacio", avatar: "/assets/icons/avatar1.png" },
    ],
    tags: ["Formación"],
  },
];
